#!/bin/sh

C_FILE="$1.c"
H_FILE="$1.h"
shift

echo "#include \"objs.h\""                        > $C_FILE
echo ""                                          >> $C_FILE

echo "#pragma once"                               > $H_FILE
echo "#include \"../../../common/src/common.h\"" >> $H_FILE
echo ""                                          >> $H_FILE

while (("$#")); do
	for filename in $1*.obj; do
		file=${filename##*/}
		file=${file%.obj}
		file=${file^}
		echo "mesh *mesh$file;" >> $C_FILE
		echo "extern mesh *mesh$file;" >> $H_FILE
	done
	shift
done
