#!/usr/bin/env bash

C_FILE="$1.c"
H_FILE="$1.h"
shift

echo "#include \"sfx.h\""                        > $C_FILE
echo ""                                          >> $C_FILE

echo "#pragma once"                               > $H_FILE
echo "#include \"../../../common/src/common.h\"" >> $H_FILE
echo ""                                          >> $H_FILE


while (("$#")); do
	for filename in $1*.aif; do
		file=${filename##*/}
		file=${file%.aif}
		file=${file^}
		echo "sfx *sfx$file;" >> $C_FILE
		echo "extern sfx *sfx$file;" >> $H_FILE
	done
	shift
done
