AS               := as
CC               := clang
LD               := clang

CFLAGS           += -D_GNU_SOURCE
LDFLAGS          += -D_GNU_SOURCE

CLIENT_CINCLUDES := $(shell sdl2-config --cflags)
CLIENT_LIBS      := $(shell sdl2-config --libs) -lm -lSDL2 -lSDL2_mixer
SERVER_LIBS      := -lm

.PHONY: all
all: wolkenwelten wolkenwelten-server
