CC = gcc

CLIENT_CINCLUDES := $(shell sdl2-config --cflags)
CLIENT_LIBS := -lnetwork $(shell sdl2-config --cflags) -lGL -lpthread -lSDL2 -lSDL2_mixer

SERVER_LIBS := -lnetwork -lm


.PHONY: all
all: wolkenwelten wolkenwelten-server
