#!/usr/bin/env bash
EMSDK_TESTED_VERSION="3.1.13"
EMSDK_REPO_URL="https://github.com/emscripten-core/emsdk.git"

cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ..
DIR=`pwd`
if [ ! -d "platform/wasm/emsdk" ]; then
	cd "platform/wasm/"
	git clone "$EMSDK_REPO_URL"
fi
cd "platform/wasm/emsdk"
git pull
./emsdk install "$EMSDK_TESTED_VERSION"
./emsdk activate "$EMSDK_TESTED_VERSION"
cd "$DIR"

source "platform/wasm/emsdk/emsdk_env.sh"
make -j release.wasm
