#!/usr/bin/env bash
cd "$(dirname "$0")"
cd ../

make clean 2> /dev/null > /dev/null
CFILES=`find client/src common/src nujel-standalone server/src tools client/tools -type f -name '*.c' ! -name 'khrplatform.[ch]' ! -name 'gl3w.[ch]' ! -name 'lz4.[ch]' ! -name 'lodepng.[ch]' ! -name 'glcorearb.[ch]'`
HFILES=`find client/src common/src nujel-standalone server/src tools client/tools -type f -name '*.h' ! -name 'khrplatform.[ch]' ! -name 'gl3w.[ch]' ! -name 'lz4.[ch]' ! -name 'lodepng.[ch]' ! -name 'glcorearb.[ch]'`
NUJFILES=`find ./ -type f -name '*.nuj' ! -name 'khrplatform.[ch]' ! -name 'gl3w.[ch]' ! -name 'lz4.[ch]' ! -name 'lodepng.[ch]' ! -name 'glcorearb.[ch]'`

CLINES=`wc -l $CFILES | tail -n1 | awk '{print $1}'`
HLINES=`wc -l $HFILES | tail -n1 | awk '{print $1}'`
NUJLINES=`wc -l $NUJFILES | tail -n1  | awk '{print $1}'`
printf 'C Source: %7s\n' "$CLINES"
printf 'C Header: %7s\n' "$HLINES"
printf 'Nujel:    %7s\n' "$NUJLINES"
