#!/usr/bin/env bash
branchname=`git rev-parse --abbrev-ref HEAD`
curcommit=`git rev-parse --short HEAD | tr '[:lower:]' '[:upper:]'`
commitdateraw=`git show -s --format=%ci "$curcommit"`
commitdate=${commitdateraw%% *}
commitcount=`git log "$branchname" --oneline --not master | wc -l`
if [[ "$branchname" =~ ^ver/.* ]]; then
	branchname="${branchname:4}"
	echo "$branchname.$commitcount"
else
	echo "$branchname-$curcommit-$commitdate"
fi
