name: Automated Builds

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: msys2/setup-msys2@v2
      name: "Initial msys2 setup"
      with:
        msystem: clang64
        install: >-
          base-devel
          p7zip
          gcc
          mingw-w64-x86_64-binutils
          mingw-w64-clang-x86_64-autotools
          mingw-w64-clang-x86_64-toolchain
          mingw-w64-clang-x86_64-cmake
          mingw-w64-clang-x86_64-ffmpeg
          mingw-w64-clang-x86_64-nasm
          mingw-w64-clang-x86_64-ninja
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - run: git config --global core.autocrlf input
      shell: bash
    - name: Compile stripped down SDL2
      run: cd platform/win/msys2_pkgs/mingw-w64-SDL2/ && export CC=clang && makepkg -i --noconfirm
    - name: Compile stripped down SDL2_mixer
      run: cd platform/win/msys2_pkgs/mingw-w64-SDL2_mixer/ && export CC=clang && makepkg -i --noconfirm
    - name: Compile Nujel
      run: make -C common/nujel -j
    - name: Build release
      run: make release.win -j
    - name: Upload build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Builds
        path: "releases/win/*.7z"
        retention-days: 7