CC               := gcc

CLIENT_CINCLUDES := $(shell sdl2-config --cflags)
CLIENT_LIBS      := -lGL -lpthread -ldl -lSDL2 -lSDL2_mixer

DYNLIBS          := -lGL -lm -lpthread -ldl -lSDL2 -lSDL2_mixer
STATICLIBS       :=

WEBEXCLUDE       += --exclude=releases/linux/wolkenwelten

.PHONY: all
all: wolkenwelten wolkenwelten-server

.PHONY:  release.linux

ifndef NOLINUXRELEASE
	release: release.linux
endif

release.linux: releases/linux/wolkenwelten-linux.tar.zstd
releases/linux/wolkenwelten-linux.tar.zstd: releases/linux/wolkenwelten/wolkenwelten
releases/linux/wolkenwelten-linux.tar.zstd: releases/linux/wolkenwelten/wolkenwelten-server
	cd releases/linux/ && tar -c wolkenwelten/ | zstd -z -19 - -o wolkenwelten-linux.tar.zstd


releases/linux/wolkenwelten/wolkenwelten: CFLAGS    += $(CLIENT_CFLAGS)
releases/linux/wolkenwelten/wolkenwelten: CINCLUDES += $(CLIENT_CINCLUDES)
releases/linux/wolkenwelten/wolkenwelten: $(CLIENT_SRCS) $(CLIENT_HDRS)
releases/linux/wolkenwelten/wolkenwelten: client/src/tmp/assets.c client/src/tmp/assets.h
releases/linux/wolkenwelten/wolkenwelten: client/src/tmp/meshassets.c client/src/tmp/meshassets.h
releases/linux/wolkenwelten/wolkenwelten: client/src/tmp/mods_tmp.c client/src/tmp/mods_tmp.h
releases/linux/wolkenwelten/wolkenwelten: client/src/tmp/objs.c client/src/tmp/objs.h
releases/linux/wolkenwelten/wolkenwelten: client/src/tmp/sfx.c client/src/tmp/sfx.h
releases/linux/wolkenwelten/wolkenwelten: common/src/tmp/cto.c common/src/tmp/cto.h
	mkdir -p releases/linux/wolkenwelten/
	$(CC) $(CLIENT_SRCS) -o $@ $(RELEASE_OPTIMIZATION) $(CFLAGS) $(CINCLUDES) $(DYNLIBS) $(STATICLIBS)
	strip -gxX $@

releases/linux/wolkenwelten/wolkenwelten-server: CFLAGS    += $(SERVER_CFLAGS)
releases/linux/wolkenwelten/wolkenwelten-server: CINCLUDES += $(SERVER_CINCLUDES)
releases/linux/wolkenwelten/wolkenwelten-server: $(SERVER_SRCS) $(SERVER_HDRS)
releases/linux/wolkenwelten/wolkenwelten-server: server/src/tmp/sfx.c server/src/tmp/sfx.h
releases/linux/wolkenwelten/wolkenwelten-server: server/src/tmp/objs.c server/src/tmp/objs.h
releases/linux/wolkenwelten/wolkenwelten-server: server/src/tmp/mods_tmp.c server/src/tmp/mods_tmp.h
releases/linux/wolkenwelten/wolkenwelten-server: common/src/tmp/cto.c common/src/tmp/cto.h
	mkdir -p releases/linux/wolkenwelten/
	musl-gcc -static $(SERVER_SRCS) -o $@ $(RELEASE_OPTIMIZATION) $(CFLAGS) $(CINCLUDES)
	strip -gxX $@
